### ISSUE TITLE
使用相对路径时出错

### ISSUE THREAD

**Issue by Nika978** [LeeAnnJ/MO-TSP-with-EA#1]
[info] processing file:  dantzig42.tsp
Traceback (most recent call last):
  File "c:/xue/code/python/MO-TSP-with-EA-main/Code/NSGA-II/main.py", line 129, in <module>
    nsga_ii_optimization(file, result_folder)
  File "c:/xue/code/python/MO-TSP-with-EA-main/Code/NSGA-II/main.py", line 77, in nsga_ii_optimization
    DIM,_,dis_matrix,edge_weight_matrix = Reader.read_tsp_file(f"{ARG.DATA_FOLDER}{tsp_file}")
  File "c:\xue\code\python\MO-TSP-with-EA-main\Code\NSGA-II\data_reader.py", line 79, in read_tsp_file
    with open(file_name,'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../../Data/dantzig42.tsp'

**Comment by LeeAnnJ** [comment]
请注意 readme 中给出的运行命令，main程序是在“NSGA-II”文件夹或者“SPEA2”文件夹下运行的，如果觉得不方便，可以在 argument.py 中更改文件的路径，感谢提出 issue~
